server:
  port: 8088
security:
    oauth2:
      client:
        client-id: test   ##客户端ID
        client-secret: test1234  ##客户端密钥
        registered-redirect-uri: https://www.baidu.com/
spring:
  jackson:
    time-zone: GMT+8
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  session:
    store-type: none
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root 
    password: 123456
    url: jdbc:mysql://localhost:3306/cecft?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
  redis:
   host: 127.0.0.1
   port: 6379
   timeout: 5000
   password:
  jpa:
    open-in-view: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate: 
        dialect: 
          storage_engine: innodb
        format_sql: true
        temp: 
          use_jdbc_metadata_defaults: false
#  redis:
#    host: localhost
#    database: 14
#    port: 6379
#    timeout: 5000
#    password: 
#    lettuce:
#      pool:
#        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 5      # 连接池中的最大空闲连接
#        min-idle: 2       # 连接池中的最小空闲连接     



    


